In [1]:
## I have accepted the challenge and wrote the code based on chapter 3 of Marsland's book 
## Machine Learning - An Algorithmic Perspective where the author describes how to write a perceptron
## The code below has 4 classical tests for perceptron - OR, AND, NOT and XOR

import numpy as np

class perceptron:
    def __init__(self, input_list, target_list, eta=0.25, iter=5, add_bias=True):
        self.inputs = input_list
        self.targets = target_list
        self.eta = eta
        self.iter = iter
        
        if add_bias:
            self.matrix = self.add_bias_node(input_list)
        else:
            self.matrix = self.inputs
        
        no_of_col = self.matrix.shape[1] #number of columns plus 1 for bias
        self.weights =np.random.rand(no_of_col, 1)*0.1-0.05
        
    #add a bias node at the beginning of the inputs (bias node has values -1)
    def add_bias_node(self, inputs):
        bias_node = -np.ones((inputs.shape[0],1))
        return np.concatenate((bias_node, inputs), axis=1)
 
    #function calculates activations = input nodes x weights (X x W), checks the thresholds and adjusts the weights
    def iteration(self, inputs, targets):
        activations = np.dot(self.matrix, self.weights)
        
        self.weights -= self.eta * np.dot(np.transpose(self.matrix), activations-targets)
        
        #thresholds
        thresholds = np.where(activations>0.5, 1, 0)
        print "Thresholds:\n", thresholds

    #train the perceptron with n iterations    
    def train(self):
        print self.inputs
        for i in xrange(1, self.iter+1):
            print "Iteration: ", i
            print "Weights:\n", self.weights
            self.iteration(self.matrix, self.targets)

##OR LOGIC
def or_logic():            
    inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
    targets = np.array([[0], [1], [1], [1]])
    or_logic = perceptron(inputs, targets)
    or_logic.train()    
    
##AND LOGIC
def and_logic():
    inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
    targets = np.array([[0], [0], [0], [1]])
    and_logic = perceptron(inputs, targets)
    and_logic.train()

##NOT LOGIC
def not_logic():
    inputs = np.array([[1], [0]])
    targets = np.array([[0], [1]])
    not_logic = perceptron(inputs, targets)
    not_logic.train()

#XOR LOGIC 
def xor_logic():
    inputs = np.array([[0,0,1],[0,1,0],[1,0,0],[1,1,0]])
    targets = np.array([[0], [1], [1], [0]])
    not_logic = perceptron(inputs, targets, add_bias=True, iter=15)
    not_logic.train()

####RUN####
or_logic()
#and_logic()
#not_logic()
#xor_logic()



[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Iteration:  1
Weights:
[[-0.038122  ]
 [-0.04242723]
 [ 0.01657218]]
Thresholds:
[[0]
 [0]
 [0]
 [0]]
Iteration:  2
Weights:
[[-0.76292752]
 [ 0.45558234]
 [ 0.4998319 ]]
Thresholds:
[[1]
 [1]
 [1]
 [1]]
Iteration:  3
Weights:
[[-0.27229288]
 [ 0.22136943]
 [ 0.2545566 ]]
Thresholds:
[[0]
 [1]
 [0]
 [1]]
Iteration:  4
Weights:
[[-0.51203698]
 [ 0.41089913]
 [ 0.4357895 ]]
Thresholds:
[[1]
 [1]
 [1]
 [1]]
Iteration:  5
Weights:
[[-0.32665569]
 [ 0.3404837 ]
 [ 0.35915148]]
Thresholds:
[[0]
 [1]
 [1]
 [1]]
